# fly.toml app configuration file generated for fp2024 on 2023-11-24T13:57:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fantapronositco"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 30

[build]
[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"
COMPOSER_ARGS= ""

[env]
APP_ENV = "production"
APP_URL="http://0.0.0.0:8080"
APP_NAME = "https://fp2024.fly.dev"
APP_LOCALE = "it"
DB_CONNECTION = "pgsql"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "debug"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
# This is needed for none file session drive as multiple instances don't look in the same place for csrf token
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
MAIL_MAILER = "smtp"
MAIL_HOST = "email-smtp.eu-north-1.amazonaws.com"
MAIL_PORT = 465
MAIL_USERNAME = "AKIAQ3EGUOY4ELVKMSVB"
MAIL_ENCRYPTION= "tls"
MAIL_FROM_ADDRESS="no-replay@support.fantapronostico.top"
MAIL_FROM_NAME="fantapronostico"

[[mounts]]
source = "storage_vol"
destination = "/var/www/html/storage"
initial_size = "1500MB"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[http_service.checks]]
grace_period = "15s"
interval = "60s"
method = "GET"
timeout = "15s"
path = "/up"
