name: frontend-ci
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Npm Dependencies
        run: npm install
      - name: Run biome linter and formatter in dry-run
        run: |
          npm run check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Npm Dependencies
        run: npm install
      - name: Run tests
        run: |
          node --test
#  e2e:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.2'
#          coverage: 'xdebug'
#      - name: Prepare The Environment
#        run: cp .env.example .env
#      - name: Install Composer Dependencies
#        run: composer install --no-progress --optimize-autoloader
#      - name: Make Database
#        run: touch ./storage/database/db_cypress.sqlite
#      - name: Run Migrations
#        run: php artisan migrate --force -n --env=cypress
#      - name: Encryption key
#        run: php artisan key:generate
#      # Install npm dependencies, cache them correctly
#      # and run all Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v6
#        with:
#          start: php artisan serve --port=8001 --env=cypress
